server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            # can also add multiple paths seperated by comma
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true